### ISSUE TITLE
请求分享数据集

### ISSUE THREAD

**Issue by magic-Alex** [wang-10086/yolov5-5.0#2]
您好，我目前在尝试进行信号机识别，您的项目对我帮助很大，不知道您是否愿意共享数据集，感谢。

**Comment by wang-10086** [comment]
非常抱歉，实验室有要求，我没有权限分享数据集，方便问下您是什么用途，我可以帮忙联系询问一下

**Comment by magic-Alex** [comment]
感谢您的回复，我计划在科研项目和论文中使用，主题是关于铁路自动化相关，后续数据集如果有分享计划，望您在此留言，感激不尽
